<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Database\Seeder;

class CarSeeder extends Seeder
{
    public function run(): void
    {
        $cars = [
            [
                'name' => '2025 Lamborghini Revuelto',
                'image' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=400&q=80',
                'price' => 45000000,
                'location' => 'Metro Manila, BGC',
                'year' => 2025,
                'mileage' => '0 km',
                'engine' => '6.5L V12 Hybrid',
                'transmission' => '8-Speed Dual-Clutch',
                'horsepower' => '1,015 HP',
                'topSpeed' => '350 km/h',
                'acceleration' => '0-100 km/h in 2.5s',
                'fuelType' => 'Hybrid',
                'color' => 'Giallo Auge (Yellow)',
                'condition' => 'Brand New',
                'description' => 'The all-new Lamborghini Revuelto - the first V12 hybrid supercar from Sant\'Agata. Revolutionary plug-in hybrid technology meets legendary V12 performance.'
            ],
            [
                'name' => '2025 Ferrari SF90 XX Stradale',
                'image' => 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=400&q=80',
                'price' => 52000000,
                'location' => 'Makati City',
                'year' => 2025,
                'mileage' => '0 km',
                'engine' => '4.0L Twin-Turbo V8 Hybrid',
                'transmission' => '8-Speed Dual-Clutch',
                'horsepower' => '1,030 HP',
                'topSpeed' => '340 km/h',
                'acceleration' => '0-100 km/h in 2.3s',
                'fuelType' => 'Hybrid',
                'color' => 'Rosso Corsa (Red)',
                'condition' => 'Brand New',
                'description' => 'Ferrari\'s most powerful road-legal car ever. The SF90 XX Stradale combines F1 technology with hybrid efficiency for unprecedented performance.'
            ],
            [
                'name' => '2025 Porsche 911 GT3 RS',
                'image' => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=400&q=80',
                'price' => 22000000,
                'location' => 'Quezon City',
                'year' => 2025,
                'mileage' => '0 km',
                'engine' => '4.0L Flat-6',
                'transmission' => '7-Speed PDK',
                'horsepower' => '525 HP',
                'topSpeed' => '296 km/h',
                'acceleration' => '0-100 km/h in 3.2s',
                'fuelType' => 'Gasoline',
                'color' => 'Python Green',
                'condition' => 'Brand New',
                'description' => 'The ultimate track-focused 911. The 2025 GT3 RS features advanced aerodynamics, lightweight construction, and the legendary naturally aspirated flat-six engine.'
            ],
            [
                'name' => '2025 McLaren 750S',
                'image' => 'https://images.unsplash.com/photo-1621135802920-133df287f89c?auto=format&fit=crop&w=400&q=80',
                'price' => 35000000,
                'location' => 'BGC, Taguig',
                'year' => 2025,
                'mileage' => '0 km',
                'engine' => '4.0L Twin-Turbo V8',
                'transmission' => '7-Speed SSG',
                'horsepower' => '750 HP',
                'topSpeed' => '332 km/h',
                'acceleration' => '0-100 km/h in 2.8s',
                'fuelType' => 'Gasoline',
                'color' => 'Volcano Orange',
                'condition' => 'Brand New',
                'description' => 'The new McLaren 750S pushes the boundaries of supercar performance. Lighter, faster, and more focused than ever before with cutting-edge British engineering.'
            ],
            [
                'name' => '2023 Lamborghini Huracán EVO',
                'image' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=400&q=80',
                'price' => 25000000,
                'location' => 'Metro Manila, BGC',
                'year' => 2023,
                'mileage' => '2,500 km',
                'engine' => '5.2L V10',
                'transmission' => '7-Speed Dual-Clutch',
                'horsepower' => '640 HP',
                'topSpeed' => '325 km/h',
                'acceleration' => '0-100 km/h in 2.9s',
                'fuelType' => 'Gasoline',
                'color' => 'Arancio Borealis (Orange)',
                'condition' => 'Excellent',
                'description' => 'Stunning Lamborghini Huracán EVO in pristine condition. This supercar features the legendary naturally aspirated V10 engine.'
            ],
            [
                'name' => '2022 Ferrari F8 Tributo',
                'image' => 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=400&q=80',
                'price' => 32000000,
                'location' => 'Makati City',
                'year' => 2022,
                'mileage' => '3,200 km',
                'engine' => '3.9L Twin-Turbo V8',
                'transmission' => '7-Speed Dual-Clutch',
                'horsepower' => '720 HP',
                'topSpeed' => '340 km/h',
                'acceleration' => '0-100 km/h in 2.9s',
                'fuelType' => 'Gasoline',
                'color' => 'Rosso Corsa (Red)',
                'condition' => 'Like New',
                'description' => 'The Ferrari F8 Tributo represents the pinnacle of Italian engineering with its twin-turbo V8 producing 720 horsepower.'
            ],
            [
                'name' => '2024 Bugatti Chiron Super Sport',
                'image' => 'https://images.unsplash.com/photo-1566023888-c8e3e5e1f8e7?auto=format&fit=crop&w=400&q=80',
                'price' => 180000000,
                'location' => 'BGC, Taguig',
                'year' => 2024,
                'mileage' => '500 km',
                'engine' => '8.0L Quad-Turbo W16',
                'transmission' => '7-Speed Dual-Clutch',
                'horsepower' => '1,600 HP',
                'topSpeed' => '440 km/h',
                'acceleration' => '0-100 km/h in 2.4s',
                'fuelType' => 'Gasoline',
                'color' => 'Atlantic Blue',
                'condition' => 'Excellent',
                'description' => 'The ultimate hypercar. Bugatti Chiron Super Sport with its legendary W16 engine delivering 1,600 horsepower. One of the fastest production cars ever made.'
            ],
            [
                'name' => '2025 Aston Martin Valkyrie',
                'image' => 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=400&q=80',
                'price' => 95000000,
                'location' => 'Makati City',
                'year' => 2025,
                'mileage' => '0 km',
                'engine' => '6.5L V12 Hybrid',
                'transmission' => '7-Speed Sequential',
                'horsepower' => '1,160 HP',
                'topSpeed' => '402 km/h',
                'acceleration' => '0-100 km/h in 2.5s',
                'fuelType' => 'Hybrid',
                'color' => 'Stirling Green',
                'condition' => 'Brand New',
                'description' => 'F1 technology for the road. The Aston Martin Valkyrie is a collaboration with Red Bull Racing, featuring Adrian Newey\'s aerodynamic genius.'
            ],
            [
                'name' => '2024 Koenigsegg Jesko Absolut',
                'image' => 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=400&q=80',
                'price' => 150000000,
                'location' => 'BGC, Taguig',
                'year' => 2024,
                'mileage' => '0 km',
                'engine' => '5.0L Twin-Turbo V8',
                'transmission' => '9-Speed Light Speed',
                'horsepower' => '1,600 HP',
                'topSpeed' => '531 km/h (theoretical)',
                'acceleration' => '0-100 km/h in 2.5s',
                'fuelType' => 'Gasoline',
                'color' => 'Jesko Orange',
                'condition' => 'Brand New',
                'description' => 'Swedish hypercar engineering at its finest. The Jesko Absolut is designed for maximum top speed with minimal drag, potentially the fastest car ever.'
            ],
            [
                'name' => '2024 Pagani Huayra R',
                'image' => 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=400&q=80',
                'price' => 125000000,
                'location' => 'Mandaluyong',
                'year' => 2024,
                'mileage' => '0 km',
                'engine' => '6.0L Twin-Turbo V12',
                'transmission' => '6-Speed Sequential',
                'horsepower' => '850 HP',
                'topSpeed' => '360 km/h',
                'acceleration' => '0-100 km/h in 2.8s',
                'fuelType' => 'Gasoline',
                'color' => 'Exposed Carbon Fiber',
                'condition' => 'Brand New',
                'description' => 'Track-only masterpiece from Pagani. The Huayra R is a work of automotive art with its naturally aspirated V12 and stunning carbon fiber body.'
            ],
            [
                'name' => '2024 Mercedes-AMG ONE',
                'image' => 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=400&q=80',
                'price' => 85000000,
                'location' => 'Quezon City',
                'year' => 2024,
                'mileage' => '0 km',
                'engine' => '1.6L Turbo V6 Hybrid',
                'transmission' => '8-Speed Automated',
                'horsepower' => '1,063 HP',
                'topSpeed' => '352 km/h',
                'acceleration' => '0-100 km/h in 2.9s',
                'fuelType' => 'Hybrid',
                'color' => 'AMG Green Hell Magno',
                'condition' => 'Brand New',
                'description' => 'F1 engine in a road car. The Mercedes-AMG ONE features the actual Formula 1 hybrid powertrain from Lewis Hamilton\'s championship-winning car.'
            ],
            [
                'name' => '2024 Rimac Nevera',
                'image' => 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=400&q=80',
                'price' => 95000000,
                'location' => 'BGC, Taguig',
                'year' => 2024,
                'mileage' => '0 km',
                'engine' => 'Quad Electric Motors',
                'transmission' => 'Single-Speed',
                'horsepower' => '1,914 HP',
                'topSpeed' => '412 km/h',
                'acceleration' => '0-100 km/h in 1.85s',
                'fuelType' => 'Electric',
                'color' => 'Nebula Green',
                'condition' => 'Brand New',
                'description' => 'The world\'s fastest electric hypercar. Croatian engineering excellence with mind-bending acceleration and cutting-edge battery technology.'
            ],
            [
                'name' => '2023 Bentley Continental GT Speed',
                'image' => 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=400&q=80',
                'price' => 28000000,
                'location' => 'Makati City',
                'year' => 2023,
                'mileage' => '1,800 km',
                'engine' => '6.0L Twin-Turbo W12',
                'transmission' => '8-Speed Dual-Clutch',
                'horsepower' => '650 HP',
                'topSpeed' => '333 km/h',
                'acceleration' => '0-100 km/h in 3.6s',
                'fuelType' => 'Gasoline',
                'color' => 'Beluga Black',
                'condition' => 'Excellent',
                'description' => 'British luxury meets supercar performance. The Continental GT Speed offers handcrafted interior, W12 power, and unmatched refinement.'
            ],
            [
                'name' => '2024 Rolls-Royce Spectre',
                'image' => 'https://images.unsplash.com/photo-1631295868223-63265b40d9e4?auto=format&fit=crop&w=400&q=80',
                'price' => 75000000,
                'location' => 'BGC, Taguig',
                'year' => 2024,
                'mileage' => '0 km',
                'engine' => 'Dual Electric Motors',
                'transmission' => 'Single-Speed',
                'horsepower' => '584 HP',
                'topSpeed' => '250 km/h',
                'acceleration' => '0-100 km/h in 4.5s',
                'fuelType' => 'Electric',
                'color' => 'Bespoke Purple',
                'condition' => 'Brand New',
                'description' => 'The first all-electric Rolls-Royce. The Spectre combines legendary luxury with silent electric power and cutting-edge technology.'
            ],
        ];

        foreach ($cars as $car) {
            Car::create($car);
        }
    }
}
